import type { Property } from "@/types"

export type { Property }

// Filter options for the sidebar
export const amenitiesList = [
  "WiFi",
  "Parking", 
  "Gym",
  "Pool",
  "Washer/Dryer",
  "Elevator",
  "Balcony",
  "Central AC",
  "Pets Allowed",
  "Fireplace",
  "Garden",
  "Patio",
  "Garage",
  "Dishwasher",
  "Microwave",
  "Refrigerator",
  "Hardwood Floors",
  "Walk-in Closets",
  "High Speed Internet"
];

export const propertyTypes = [
  "Apartment",
  "Villa", 
  "Townhouse",
  "Cottage"
];

export const properties: Property[] = [
  {
    id: 1,
    title: "Modern Luxury Apartment with City Views",
    description: "Experience urban living at its finest in this stunning apartment featuring floor-to-ceiling windows with panoramic city views. This newly renovated unit offers an open-concept living space, gourmet kitchen with stainless steel appliances, and a private balcony perfect for morning coffee or evening relaxation.",
    price: 2500,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1200,
    propertyType: "Apartment",
    photoUrls: ["/placeholder.jpg"],
    amenities: ["WiFi", "Parking", "Gym", "Pool", "Washer/Dryer", "Elevator", "Balcony", "Central AC"],
    highlights: ["City Views", "Newly Renovated", "Private Balcony"],
    location: { 
      address: "123 Downtown Ave", 
      city: "Metropolis", 
      state: "CA", 
      country: "USA",
      coordinates: {
        lat: 34.0522,
        lng: -118.2437,
        latitude: 34.0522,
        longitude: -118.2437
      }
    },
    // Backend compatibility fields
    name: "Modern Luxury Apartment with City Views",
    pricePerMonth: 2500,
    beds: 2,
    baths: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: 2,
    title: "Charming Cottage with Private Garden",
    description: "Escape the hustle and bustle in this idyllic cottage surrounded by lush greenery. This charming home features original hardwood floors, a cozy fireplace, and a fully updated kitchen with quartz countertops.",
    price: 1800,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 950,
    propertyType: "Cottage",
    photoUrls: ["/placeholder.jpg"],
    amenities: ["Parking", "Pets Allowed", "Washer/Dryer", "Fireplace", "Garden", "Patio"],
    highlights: ["Private Garden", "Hardwood Floors", "Cozy Fireplace"],
    location: { 
      address: "456 Willow Lane", 
      city: "Greenfield", 
      state: "OR", 
      country: "USA",
      coordinates: {
        lat: 45.3311,
        lng: -122.9015,
        latitude: 45.3311,
        longitude: -122.9015
      }
    },
    name: "Charming Cottage with Private Garden",
    pricePerMonth: 1800,
    beds: 2,
    baths: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: 3,
    title: "Spacious Townhouse with Garage",
    description: "This elegant townhouse offers the perfect blend of comfort and convenience. The three-level home features an open-concept main floor with hardwood flooring, a gourmet kitchen with island seating, and a bright living area.",
    price: 2200,
    bedrooms: 3,
    bathrooms: 2.5,
    squareFeet: 1800,
    propertyType: "Townhouse",
    photoUrls: ["/placeholder.jpg"],
    amenities: ["WiFi", "Parking", "Washer/Dryer", "Garage", "Patio", "Central AC", "Dishwasher"],
    highlights: ["Three Levels", "Gourmet Kitchen", "Garage Included"],
    location: { 
      address: "789 Oak Street", 
      city: "Riverside", 
      state: "TX", 
      country: "USA",
      coordinates: {
        lat: 32.7767,
        lng: -96.7970,
        latitude: 32.7767,
        longitude: -96.7970
      }
    },
    name: "Spacious Townhouse with Garage",
    pricePerMonth: 2200,
    beds: 3,
    baths: 2.5,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: 4,
    title: "Elegant Villa with Pool",
    description: "Indulge in luxury living in this magnificent villa featuring a private pool and extensive outdoor entertaining areas. The open-plan design seamlessly connects indoor and outdoor spaces, with high-end finishes throughout.",
    price: 3500,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2500,
    propertyType: "Villa",
    photoUrls: ["/placeholder.jpg"],
    amenities: ["WiFi", "Parking", "Pool", "Gym", "Washer/Dryer", "Garden", "Patio", "Central AC", "Fireplace"],
    highlights: ["Private Pool", "Luxury Finishes", "Outdoor Entertainment"],
    location: { 
      address: "321 Palm Drive", 
      city: "Sunset Hills", 
      state: "FL", 
      country: "USA",
      coordinates: {
        lat: 25.7617,
        lng: -80.1918,
        latitude: 25.7617,
        longitude: -80.1918
      }
    },
    name: "Elegant Villa with Pool",
    pricePerMonth: 3500,
    beds: 4,
    baths: 3,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z"
  },
  {
    id: 5,
    title: "Cozy Studio Downtown",
    description: "Perfect for young professionals or students, this cozy studio apartment offers everything you need in a compact, efficient space. Located in the vibrant downtown area, you'll be within walking distance of cafes, restaurants, and public transportation.",
    price: 1200,
    bedrooms: 0,
    bathrooms: 1,
    squareFeet: 450,
    propertyType: "Apartment",
    location: { address: "654 City Center Blvd", city: "Metropolis", state: "CA", zip: "90002" },
    availableFrom: "2024-05-01",
    amenities: ["WiFi", "Elevator", "Central AC", "Washer/Dryer"],
    images: [],
    isFeatured: false,
  },
  {
    id: 6,
    title: "Family-Friendly Townhouse",
    description: "This spacious townhouse is perfect for families, featuring a large backyard, modern kitchen, and plenty of storage space. Located in a quiet neighborhood with excellent schools nearby.",
    price: 2000,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1600,
    propertyType: "Townhouse",
    location: { address: "147 Maple Avenue", city: "Greenfield", state: "OR", zip: "97302" },
    availableFrom: "2024-06-15",
    amenities: ["WiFi", "Parking", "Washer/Dryer", "Garden", "Patio", "Pets Allowed", "Central AC"],
    images: [],
    isFeatured: false,
  },
  {
    id: 7,
    title: "Urban Loft with Exposed Brick",
    description: "Industrial chic meets modern comfort in this stunning loft featuring exposed brick walls, high ceilings, and large windows. Perfect for creative professionals seeking an inspiring living space.",
    price: 2800,
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 1100,
    propertyType: "Apartment",
    location: { address: "888 Industrial Way", city: "Brooklyn", state: "NY", zip: "11201" },
    availableFrom: "2024-06-01",
    amenities: ["WiFi", "Parking", "Elevator", "Hardwood Floors", "High Speed Internet"],
    images: [],
    isFeatured: false,
  },
  {
    id: 8,
    title: "Waterfront Condo with Marina Views",
    description: "Wake up to breathtaking marina views in this luxurious waterfront condo. Features include a private balcony, modern appliances, and access to resort-style amenities including a rooftop pool.",
    price: 4200,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1400,
    propertyType: "Apartment",
    location: { address: "200 Marina Boulevard", city: "San Diego", state: "CA", zip: "92101" },
    availableFrom: "2024-07-15",
    amenities: ["WiFi", "Pool", "Gym", "Balcony", "Parking", "Elevator", "Central AC"],
    images: [],
    isFeatured: true,
  },
  {
    id: 9,
    title: "Historic Brownstone Apartment",
    description: "Step into history with this beautifully preserved brownstone apartment featuring original details, hardwood floors, and modern updates. Located in a tree-lined historic district.",
    price: 3200,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1900,
    propertyType: "Apartment",
    location: { address: "567 Heritage Street", city: "Boston", state: "MA", zip: "02115" },
    availableFrom: "2024-08-01",
    amenities: ["WiFi", "Parking", "Hardwood Floors", "Fireplace", "Walk-in Closets"],
    images: [],
    isFeatured: false,
  },
  {
    id: 10,
    title: "Mountain View Cabin",
    description: "Escape to nature in this cozy cabin with stunning mountain views. Features a wraparound deck, stone fireplace, and fully equipped kitchen. Perfect for those seeking tranquility.",
    price: 1900,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 1000,
    propertyType: "Cottage",
    location: { address: "123 Mountain Road", city: "Aspen", state: "CO", zip: "81611" },
    availableFrom: "2024-05-01",
    amenities: ["WiFi", "Parking", "Fireplace", "Patio", "Garden"],
    images: [],
    isFeatured: false,
  },
  {
    id: 11,
    title: "Luxury Penthouse Suite",
    description: "Experience the pinnacle of luxury living in this stunning penthouse with panoramic city views, private elevator access, and a rooftop terrace. Features premium finishes throughout.",
    price: 6500,
    bedrooms: 3,
    bathrooms: 3,
    squareFeet: 2800,
    propertyType: "Apartment",
    location: { address: "1 Skyline Plaza", city: "Chicago", state: "IL", zip: "60601" },
    availableFrom: "2024-09-01",
    amenities: ["WiFi", "Pool", "Gym", "Elevator", "Balcony", "Central AC", "Garage"],
    images: [],
    isFeatured: true,
  },
  {
    id: 12,
    title: "Suburban Family Home",
    description: "Perfect family home in a quiet suburban neighborhood. Features a large yard, modern kitchen, and three bedrooms. Close to top-rated schools and shopping centers.",
    price: 2400,
    bedrooms: 4,
    bathrooms: 2.5,
    squareFeet: 2200,
    propertyType: "Villa",
    location: { address: "789 Suburban Lane", city: "Plano", state: "TX", zip: "75023" },
    availableFrom: "2024-06-01",
    amenities: ["WiFi", "Parking", "Garden", "Patio", "Garage", "Central AC"],
    images: [],
    isFeatured: false,
  },
  {
    id: 13,
    title: "Beachside Bungalow",
    description: "Just steps from the beach, this charming bungalow offers the perfect coastal retreat. Features an open floor plan, deck with ocean views, and beach access.",
    price: 3800,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1300,
    propertyType: "Cottage",
    location: { address: "456 Ocean Drive", city: "Malibu", state: "CA", zip: "90265" },
    availableFrom: "2024-07-01",
    amenities: ["WiFi", "Parking", "Balcony", "Patio", "Central AC"],
    images: [],
    isFeatured: true,
  },
  {
    id: 14,
    title: "Modern High-Rise Studio",
    description: "Contemporary studio in a luxury high-rise building. Features floor-to-ceiling windows, modern appliances, and access to building amenities including fitness center and rooftop deck.",
    price: 1800,
    bedrooms: 0,
    bathrooms: 1,
    squareFeet: 550,
    propertyType: "Apartment",
    location: { address: "300 Tower Street", city: "Seattle", state: "WA", zip: "98101" },
    availableFrom: "2024-05-15",
    amenities: ["WiFi", "Gym", "Pool", "Elevator", "Central AC"],
    images: [],
    isFeatured: false,
  },
  {
    id: 15,
    title: "Garden Apartment with Patio",
    description: "Ground-floor apartment with private patio and garden access. Features updated kitchen, hardwood floors, and abundant natural light. Pet-friendly with nearby dog park.",
    price: 2100,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 1050,
    propertyType: "Apartment",
    location: { address: "234 Garden Court", city: "Portland", state: "OR", zip: "97205" },
    availableFrom: "2024-08-15",
    amenities: ["WiFi", "Parking", "Patio", "Garden", "Pets Allowed", "Hardwood Floors"],
    images: [],
    isFeatured: false,
  },
  {
    id: 16,
    title: "Executive Townhome",
    description: "Upscale townhome in gated community. Features three levels, master suite with walk-in closet, finished basement, and two-car garage. Community amenities include pool and tennis court.",
    price: 3200,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2400,
    propertyType: "Townhouse",
    location: { address: "567 Executive Way", city: "Raleigh", state: "NC", zip: "27612" },
    availableFrom: "2024-07-01",
    amenities: ["WiFi", "Pool", "Garage", "Patio", "Central AC", "Walk-in Closets"],
    images: [],
    isFeatured: true,
  },
  {
    id: 17,
    title: "Artist Loft in Arts District",
    description: "Spacious loft in the heart of the arts district. Features soaring ceilings, concrete floors, large windows, and an open floor plan perfect for creative work.",
    price: 2600,
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 1400,
    propertyType: "Apartment",
    location: { address: "890 Arts Avenue", city: "Los Angeles", state: "CA", zip: "90014" },
    availableFrom: "2024-06-15",
    amenities: ["WiFi", "Parking", "High Speed Internet", "Hardwood Floors"],
    images: [],
    isFeatured: false,
  },
  {
    id: 18,
    title: "Lakefront Cottage",
    description: "Peaceful lakefront cottage with private dock and beach access. Features rustic charm with modern amenities, stone fireplace, and screened porch overlooking the water.",
    price: 2800,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1600,
    propertyType: "Cottage",
    location: { address: "123 Lakeside Drive", city: "Lake Tahoe", state: "CA", zip: "96150" },
    availableFrom: "2024-09-01",
    amenities: ["WiFi", "Parking", "Fireplace", "Patio", "Garden"],
    images: [],
    isFeatured: true,
  },
  {
    id: 19,
    title: "Downtown Luxury Condo",
    description: "Sophisticated condo in premier downtown building. Features marble countertops, stainless steel appliances, city views, and concierge services. Walking distance to restaurants and shopping.",
    price: 4800,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1600,
    propertyType: "Apartment",
    location: { address: "777 Downtown Plaza", city: "Miami", state: "FL", zip: "33131" },
    availableFrom: "2024-08-01",
    amenities: ["WiFi", "Pool", "Gym", "Elevator", "Balcony", "Central AC"],
    images: [],
    isFeatured: true,
  },
  {
    id: 20,
    title: "Cozy Duplex with Yard",
    description: "Charming duplex with private entrance and fenced yard. Features updated kitchen, hardwood floors, and washer/dryer hookups. Perfect for small families or professionals.",
    price: 1900,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 1100,
    propertyType: "Townhouse",
    location: { address: "456 Duplex Street", city: "Austin", state: "TX", zip: "78704" },
    availableFrom: "2024-06-01",
    amenities: ["WiFi", "Parking", "Washer/Dryer", "Garden", "Pets Allowed"],
    images: [],
    isFeatured: false,
  },
  {
    id: 21,
    title: "Luxury Villa with Pool",
    description: "Stunning villa with resort-style amenities including pool, spa, and outdoor kitchen. Features marble floors, gourmet kitchen, and master suite with sitting area.",
    price: 5200,
    bedrooms: 5,
    bathrooms: 4,
    squareFeet: 3500,
    propertyType: "Villa",
    location: { address: "999 Villa Court", city: "Scottsdale", state: "AZ", zip: "85251" },
    availableFrom: "2024-10-01",
    amenities: ["WiFi", "Pool", "Garage", "Patio", "Garden", "Central AC", "Fireplace"],
    images: [],
    isFeatured: true,
  },
  {
    id: 22,
    title: "University Area Apartment",
    description: "Perfect for students or young professionals. Clean, safe apartment near university campus with easy access to public transportation. Recently renovated with modern amenities.",
    price: 1400,
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 700,
    propertyType: "Apartment",
    location: { address: "789 University Avenue", city: "Madison", state: "WI", zip: "53706" },
    availableFrom: "2024-08-15",
    amenities: ["WiFi", "Parking", "Washer/Dryer", "Central AC"],
    images: [],
    isFeatured: false,
  },
  {
    id: 23,
    title: "Historic Mansion Apartment",
    description: "Elegant apartment in converted historic mansion. Features high ceilings, original architectural details, updated kitchen, and beautiful common areas including library and garden.",
    price: 2900,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 1300,
    propertyType: "Apartment",
    location: { address: "123 Historic Row", city: "Charleston", state: "SC", zip: "29401" },
    availableFrom: "2024-09-15",
    amenities: ["WiFi", "Parking", "Garden", "Hardwood Floors", "Fireplace"],
    images: [],
    isFeatured: false,
  },
  {
    id: 24,
    title: "Modern Farmhouse",
    description: "Contemporary farmhouse on spacious lot with barn-style details and modern amenities. Features open floor plan, farmhouse sink, and large covered porch perfect for entertaining.",
    price: 3600,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2600,
    propertyType: "Villa",
    location: { address: "456 Farmhouse Lane", city: "Franklin", state: "TN", zip: "37064" },
    availableFrom: "2024-07-15",
    amenities: ["WiFi", "Parking", "Garden", "Patio", "Garage", "Central AC"],
    images: [],
    isFeatured: true,
  },
  {
    id: 25,
    title: "Riverside Apartment",
    description: "Scenic apartment overlooking the river with walking trails and park access. Features balcony with river views, updated appliances, and quiet location away from city traffic.",
    price: 2300,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1250,
    propertyType: "Apartment",
    location: { address: "789 Riverside Drive", city: "Richmond", state: "VA", zip: "23220" },
    availableFrom: "2024-06-01",
    amenities: ["WiFi", "Parking", "Balcony", "Central AC", "Washer/Dryer"],
    images: [],
    isFeatured: false,
  },
  {
    id: 26,
    title: "Mountain Cabin Retreat",
    description: "Rustic mountain cabin perfect for nature lovers. Features wood-burning fireplace, wraparound deck, and mountain views. Close to hiking trails and ski resorts.",
    price: 2200,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1500,
    propertyType: "Cottage",
    location: { address: "321 Mountain View Road", city: "Breckenridge", state: "CO", zip: "80424" },
    availableFrom: "2024-11-01",
    amenities: ["WiFi", "Parking", "Fireplace", "Patio", "Garden"],
    images: [],
    isFeatured: false,
  },
  {
    id: 27,
    title: "Golf Course Townhome",
    description: "Elegant townhome overlooking the 18th hole with golf course and mountain views. Features vaulted ceilings, gourmet kitchen, and private patio with golf course access.",
    price: 3800,
    bedrooms: 3,
    bathrooms: 2.5,
    squareFeet: 2100,
    propertyType: "Townhouse",
    location: { address: "654 Golf Club Drive", city: "Palm Springs", state: "CA", zip: "92262" },
    availableFrom: "2024-10-15",
    amenities: ["WiFi", "Pool", "Garage", "Patio", "Central AC"],
    images: [],
    isFeatured: true,
  },
  {
    id: 28,
    title: "Urban Rooftop Apartment",
    description: "Unique apartment with private rooftop terrace in trendy neighborhood. Features exposed brick, modern kitchen, and panoramic city views from the rooftop deck.",
    price: 3400,
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 1200,
    propertyType: "Apartment",
    location: { address: "987 Urban Street", city: "Denver", state: "CO", zip: "80202" },
    availableFrom: "2024-08-01",
    amenities: ["WiFi", "Parking", "Balcony", "Hardwood Floors", "High Speed Internet"],
    images: [],
    isFeatured: false,
  },
  {
    id: 29,
    title: "Coastal Cottage with Deck",
    description: "Charming coastal cottage just blocks from the beach. Features nautical decor, outdoor shower, large deck perfect for entertaining, and easy beach access.",
    price: 3200,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1400,
    propertyType: "Cottage",
    location: { address: "159 Coastal Road", city: "Cape Cod", state: "MA", zip: "02601" },
    availableFrom: "2024-05-01",
    amenities: ["WiFi", "Parking", "Patio", "Garden", "Central AC"],
    images: [],
    isFeatured: true,
  },
  {
    id: 30,
    title: "Metropolitan High-Rise",
    description: "Sophisticated apartment on the 25th floor with stunning city skyline views. Features floor-to-ceiling windows, marble bathroom, and access to building amenities including sky lounge.",
    price: 4500,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1500,
    propertyType: "Apartment",
    location: { address: "753 Metropolitan Avenue", city: "Atlanta", state: "GA", zip: "30309" },
    availableFrom: "2024-09-01",
    amenities: ["WiFi", "Pool", "Gym", "Elevator", "Balcony", "Central AC", "Garage"],
    images: [],
    isFeatured: true,
  },
]